author: eccentric_nz
description: Custom ores using item frames and resource pack custom models - with block break animations, custom drops and smelting.
main: me.eccentric_nz.ores.Ores
name: Ores
load: STARTUP
version: 1.0.0
api-version: 1.18
website: http://tardisjenkins.duckdns.org:8080/job/ores
dev-url: http://tardisjenkins.duckdns.org:8080/job/ores
permissions:
  ores.announce:
    description: Allow players to receive a message with the number of ores when starting to mine an ore vein.
    default: op
  ores.hud:
    description: Permission to use the /hud command.
    default: op
  ores.use:
    description: Permission to use the /ore and /pipe commands.
    default: op
commands:
  hud:
    description: Turn on the target block HUD.
    usage: /<command> [custom|vanilla]
    permission: ores.hud
    permission-message: You don't have the permission <permission> to use this command
  ore:
    description: Spawn in an ore where the player is looking.
    usage: /<command> [ore type]
    permission: ores.use
    permission-message: You don't have the permission <permission> to use this command
  pipe:
    description: Spawn in a pipe where the player is looking or set the pipe type and rotation.
    usage: /<command> [shape]
    permission: ores.use
    permission-message: You don't have the permission <permission> to use this command
